---
abstract: 'Convert and spell Thai numbers.'
author:
  - 'Guillaume Aubert <aubertg@cpan.org>'
build_requires:
  Test::Exception: '0'
  Test::FailWarnings: '0'
  Test::More: '0.94'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.140640'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Lingua-TH-Numbers
provides:
  Lingua::TH::Numbers:
    file: lib/Lingua/TH/Numbers.pm
    version: v1.0.8
requires:
  Carp: '0'
  perl: '5.008'
resources:
  bugtracker: https://github.com/guillaumeaubert/Lingua-TH-Numbers/issues
  homepage: https://metacpan.org/release/Lingua-TH-Numbers
  license: http://www.gnu.org/licenses/gpl-3.0.txt
  repository: https://github.com/guillaumeaubert/Lingua-TH-Numbers
version: v1.0.8
