---
abstract: "Convert and spell Thai numbers."
author:
  - 'Guillaume Aubert <aubertg@cpan.org>'
build_requires:
  Carp: 0
  Data::Dumper: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-TH-Numbers
provides:
  Lingua::TH::Number:
    file: lib/Lingua/TH/Numbers.pm
    version: 1.0.0
requires:
  perl: 5.006
resources:
  license: http://opensource.org/licenses/artistic-license.php
version: 1.0.0
