---
abstract: 'Convert and spell Thai numbers.'
author:
  - 'Guillaume Aubert <aubertg@cpan.org>'
build_requires:
  Test::Exception: 0
  Test::More: 0.94
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-TH-Numbers
provides:
  Lingua::TH::Numbers:
    file: lib/Lingua/TH/Numbers.pm
    version: v1.0.4
requires:
  Carp: 0
  Data::Dumper: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/NoAuth/ReportBug.html?Queue=lingua-th-numbers
  homepage: https://metacpan.org/release/Lingua-TH-Numbers
  license: http://www.perlfoundation.org/artistic_license_1_0
  repository: https://github.com/guillaumeaubert/Lingua-TH-Numbers
version: v1.0.4
